apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zerofiltretech-dev
  name: zerofiltretech-blog-dev
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 120
  replicas: 1
  selector:
    matchLabels:
      app: zerofiltretech-blog-dev
  template:
    metadata:
      labels:
        app: zerofiltretech-blog-dev
    spec:
      containers:
        - name: redis-dev
          image: redis
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
        - name: zerofiltretech-blog-dev
          image: imzerofiltre/zerofiltretech-blog:3-unstable
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zerofiltre-blog-api
                  key: spring_mail_password
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zerofiltre-blog-api
                  key: spring_datasource_password
            - name: SECURITY_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: zerofiltre-blog-api
                  key: security_jwt_secret
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: zerofiltre-blog-api
                  key: github_client_secret
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: logging_level_org_springframework
            - name: LOGGING_LEVEL_ORG_HIBERNATE_SQL
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: logging_level_org_hibernate_sql
            - name: LOGGING_LEVEL_TECH_ZEROFILTRE
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: logging_level_tech_zerofiltre
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: server_port
            - name: SPRING_LIQUIBASE_CHANGELOG
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: spring_liquibase_changelog
            - name: SPRING_MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: spring_mail_host
            - name: SPRING_MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: spring_mail_port
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: spring_mail_username
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: spring_datasource_username
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: spring_datasource_url
            - name: HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: hibernate_ddl_auto
            - name: ZEROFILTRE_ENV
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: zerofiltre_env
            - name: SECURITY_JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: security_jwt_expiration
            - name: SECURITY_JWT_URI
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: security_jwt_uri
            - name: GITHUB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: github_client_id
            - name: STACKOVERFLOW_KEY
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: stackoverflow_key
            - name: ALLOWED_ORIGINS_PATTERN
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: allowed_origins_pattern
            - name: REMINDER_RATE
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: reminder_rate
            - name: REMINDER_INITIAL_DELAY
              valueFrom:
                configMapKeyRef:
                  name: zerofiltre-blog-api
                  key: reminder_initial_delay