logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    tech:
      zerofiltre: INFO
server:
  port: 80

springdoc:
  packagesToScan: tech.zerofiltre.blog
  pathsToMatch: /**

spring:
  liquibase:
    change-log: classpath:/liquibase/db/changelog/db.changelog-prod.yaml
zerofiltre:
  infra:
    api:
      github:
        root-url: https://api.github.com/
        client-id: 844176f44da589a27331
        client-secret: 984ca15be4e5cb78154e01db8ce666a0225d60e8
      stackoverflow:
        version: 2.3
        root-url: https://api.stackexchange.com/
        key: ZAeo5W0MnZPxiEBgb99MvA((
    entrypoints:
      rest:
        api-version: 1.0
        allowed-origins-pattern: "https://blog.zerofiltre.tech"
    rate: 864000000 #10 days
    initial-delay: 864000000 #10 days
