logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework: DEBUG
    tech:
      zerofiltre: DEBUG
server:
  port: 80

spring:
  datasource:
    username: blog-api-uat
    password: h4rC5bepK7WvgrLE
    url: jdbc:mysql://mysql-df836d42-o3bc71320.database.cloud.ovh.net:20184/blogapidb
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
springdoc:
  packagesToScan: tech.zerofiltre.blog
  pathsToMatch: /**

zerofiltre:
  infra:
    entrypoints:
      rest:
        api-version: 1.0
        allowed-origins-pattern: "https://blog-uat.zerofiltre.tech"