logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework: DEBUG
    tech:
      zerofiltre: DEBUG
server:
  port: 80



spring:
  mvc:
    log-request-details: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  mail:
    host: smtp.gmail.com
    port: 587
    username: philippesimo@zerofiltre.tech
    password: upoafthyaafaadzr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    username: blog-api-uat
    password: h4rC5bepK7WvgrLE
    url: jdbc:mysql://mysql-df836d42-o3bc71320.database.cloud.ovh.net:20184/blogapidb_dev
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

springdoc:
  packagesToScan: tech.zerofiltre.blog
  pathsToMatch: /**

zerofiltre:
  infra:
    api:
      stackoverflow:
        version: 2.3
        root-url: https://api.stackexchange.com/
        key: ZAeo5W0MnZPxiEBgb99MvA((
    entrypoints:
      rest:
        api-version: 1.0
        allowed-origins-pattern: "*"
    rate: 864000000 #10 days
    initial-delay: 864000000 #10 days


