logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
    tech:
      zerofiltre: DEBUG
server:
  port: 80



spring:
  liquibase:
    change-log: classpath:/liquibase/db/changelog/db.changelog-dev.yaml
  mvc:
    log-request-details: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: philippesimo@zerofiltre.tech
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    username: blog-api-uat
    password: h4rC5bepK7WvgrLE
    url: jdbc:mysql://mysql-df836d42-o3bc71320.database.cloud.ovh.net:20184/blogapidb_dev
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update


  messages:
    fallback-to-system-locale: false
    basename: i18n.messages

springdoc:
  packagesToScan: tech.zerofiltre.blog
  pathsToMatch: /**

zerofiltre:
  env: dev
  infra:
    security:
      jwt:
        expiration: 1440 #minutes
        secret: JwtSecretKey
        prefix: Bearer
        header: Authorization
        uri: /auth/**
    api:
      github:
        root-url: https://api.github.com/
        client-id: 9b6bffa9841d19dfd8aa
        client-secret: 1e70ed907875eb633f6232235e4c4037888d0adb
      stackoverflow:
        version: 2.3
        root-url: https://api.stackexchange.com/
        key: ZAeo5W0MnZPxiEBgb99MvA((
    entrypoints:
      rest:
        api-version: 1.0
        allowed-origins-pattern: "*"
    reminder-rate: 864000000 #10 days
    reminder-initial-delay: 864000000 #10 days
    max-attempts: 2


