logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    tech:
      zerofiltre: DEBUG
server:
  port: 80

spring:
  datasource:
    username: blog-api-uat
    password: h4rC5bepK7WvgrLE
    url: jdbc:mysql://mysql-df836d42-o3bc71320.database.cloud.ovh.net:20184/blogapidb_dev
  jpa:
    generate-ddl: false
#    hibernate:
#      ddl-auto: create-drop

springdoc:
  packagesToScan: tech.zerofiltre.blog
  pathsToMatch: /**

zerofiltre:
  infra:
    entrypoints:
      rest:
        allowed-origins-pattern: "*"
