logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    tech:
      zerofiltre: INFO
server:
  port: 80

springdoc:
  packagesToScan: tech.zerofiltre.blog
  pathsToMatch: /**

zerofiltre:
  infra:
    entrypoints:
      rest:
        allowed-origins-pattern: "https://blog.zerofiltre.tech"