logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    tech:
      zerofiltre: INFO
server:
  port: 80

springdoc:
  packagesToScan: tech.zerofiltre.blog
  pathsToMatch: /**

zerofiltre:
  infra:
    entrypoints:
      rest:
        api-version: 1.0
        allowed-origins-pattern: "https://blog.zerofiltre.tech"
    rate: 864000000 #10 days
    initial-delay: 864000000 #10 days
