logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework: DEBUG
    tech:
      zerofiltre: DEBUG
server:
  port: 80

spring:
  datasource:
    username: blog-api-uat
    password: h4rC5bepK7WvgrLE
    url: jdbc:mysql://mysql-df836d42-o3bc71320.database.cloud.ovh.net:20184/blogapidb
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
springdoc:
  packagesToScan: tech.zerofiltre.blog
  pathsToMatch: /**

zerofiltre:
  infra:
    api:
      github:
        root-url: https://api.github.com/
        client-id: dee4a78da7c2c935ae27
        client-secret: 4ea099c70ab8f55321c8651adb46730f2ef3f6ad
      stackoverflow:
        version: 2.3
        root-url: https://api.stackexchange.com/
        key: ZAeo5W0MnZPxiEBgb99MvA((
    entrypoints:
      rest:
        api-version: 1.0
        allowed-origins-pattern: "https://blog-uat.zerofiltre.tech"
    rate: 864000000 #10 days
    initial-delay: 864000000 #10 days
